## Themes

#* Night Owl:
# Original VS Code Theme: https://github.com/sdras/night-owl-vscode-theme
# Alacritty Binding: https://github.com/nik27/night-owl-alacritty-theme
# File Path: ./themes/night-owl.toml

import = [
"~/.config/alacritty/themes/night-owl.toml",
# "~/.config/alacritty/themes/mertssmnoglu.toml",
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
    { key = "*", mods = "Control", action="IncreaseFontSize"},
]
