[colors.bright]
black = "#b4b4b4"
blue = "#b3d2ff"
cyan = "#c2fefa"
green = "#e3f7a1"
magenta = "#e5bdff"
red = "#f99f92"
white = "#ffffff"
yellow = "#f2e9bf"

[colors.normal]
black = "#000000"
blue = "#6ebaf8"
cyan = "#90fdf8"
green = "#bde97c"
magenta = "#ef88ff"
red = "#f7786d"
white = "#e5e1d8"
yellow = "#efdfac"

[colors.primary]
background = "#0E21A0"
foreground = "#e5e1d8"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.4

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
    { key = "*", mods = "Control", action="IncreaseFontSize"},
]
