window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.40

scrolling:
  history: 10000
  multiplier: 3

selection:
  save_to_clipboard: true

shell:
  program: /usr/bin/fish

colors:
  primary:
    background: '#0E21A0'
    foreground: '#e5e1d8'

  normal:
    black: '#000000'
    red: '#f7786d'
    green: '#bde97c'
    yellow: '#efdfac'
    blue: '#6ebaf8'
    magenta: '#ef88ff'
    cyan: '#90fdf8'
    white: '#e5e1d8'

  bright:
    black: '#b4b4b4'
    red: '#f99f92'
    green: '#e3f7a1'
    yellow: '#f2e9bf'
    blue: '#b3d2ff'
    magenta: '#e5bdff'
    cyan: '#c2fefa'
    white: '#ffffff'

